plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Weapons.md
  - Classes/Dragon.md
  - Classes/Hydra.md
  - Classes/Griffin.md
  - _/craneswing.jpg
  - _/dragonsclaw.jpg
  - _/snakesfang.jpg
theme: minima
minima:
  skin: dark