title: notdnd
subtitle: it's not dnd
description: ...
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Weapons.md
  - Classes/Dragon.md
  - Classes/Hydra.md
  - Classes/Griffin.md
theme: minima
minima:
  skin: dark
header_pages:
  - Rules.md
  - Classes/Dragon.md
  - Classes/Hydra.md
  - Classes/Griffin.md
  - World/Characters.md
  - World/Monsters.md
  - World/Weapons.md
footer:
