plugins:
  - jekyll-relative-links
  - jekyll-readme-index
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Weapons.md
  - Classes/Dragon.md
  - Classes/Hydra.md
  - Classes/Griffin.md
theme: minima
minima:
  skin: dark
