plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Weapons.md
  - Classes/Dragon.md
  - Classes/Hydra.md
  - Classes/Griffin.md
theme: minima
minima:
  skin: dark
header_pages:
  - Classes/Dragon.md
  - Classes/Hydra.md
  - Classes/Griffin.md
  - Weapons.md
